In [91]:
import pandas as pd

df = pd.read_csv('Sandy_Springs_Police_Department - Sandy_Springs_Police_Department.csv')

df.head()
df.shape
df['parent_incident_type'].describe()

count       83533
unique         20
top       Traffic
freq        23024
Name: parent_incident_type, dtype: object

Prediction: parent_incident_type

day_of_week
incident_datetime (split it month and year)
hour_of_day
longitude
latitude

In [92]:
df.dtypes  #check datatypes to identify unwanted rows

#need to convert incident_datetime, day_of_week

incident_id                int64
case_number                int64
incident_datetime         object
incident_type_primary     object
incident_description      object
clearance_type           float64
address_1                 object
address_2                float64
city                      object
state                     object
zip                       object
country                  float64
latitude                 float64
longitude                float64
created_at                object
updated_at                object
location                  object
hour_of_day                int64
day_of_week               object
parent_incident_type      object
Beats Shapes             float64
dtype: object

In [93]:
month = []
year = []
for datetime in df.incident_datetime:
    month = month + [(int(datetime[0:2]))]
    year = year + [int(datetime[6:10])]
df['incident_month'] = month
df['incident_year'] = year

In [94]:
df['day_of_week'] = df['day_of_week'].map({'Sunday': 0, 'Monday': 1, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 4, 'Friday': 5, 'Saturday': 6}).astype(int)
df.head()

,incident_id,case_number,incident_datetime,incident_type_primary,incident_description,clearance_type,address_1,address_2,city,state,...,longitude,created_at,updated_at,location,hour_of_day,day_of_week,parent_incident_type,Beats Shapes,incident_month,incident_year
0,952728267,2020000781,01/17/2020 13:30,[SSPD]-LARCENY-FROM VEHICLE,LARCENY - FROM VEHICLE,NaN,6400 Block POWERS FERRY RD,NaN,SANDY SPRINGS,GA,...,-84.435246,1/17/2020 22:37,1/17/2020 23:39,POINT (-84.43524649609589 33.90319187235206),13,5,Theft from Vehicle,212688.0,1,2020
1,952728268,2020000768,01/17/2020 12:10,[SSPD]-LARCENY - OTHER OFFENSES,LARCENY - OTHER OFFENSES,NaN,1100 Block PERIMETER CTR W,NaN,SANDY SPRINGS,GA,...,-84.351129,1/17/2020 22:37,1/17/2020 23:39,POINT (-84.35112853386204 33.93003140731569),12,5,Theft,212689.0,1,2020
2,952704703,2020000743,01/17/2020 2:14,[SSPD]-DUI - ALCOHOL,DUI - ALCOHOL,NaN,400 Block & WINDSOR PKWY,NaN,SANDY SPRINGS,GA,...,-84.364235,1/17/2020 14:38,1/17/2020 23:39,POINT (-84.3642353179997 33.89505417513069),2,5,Traffic,212685.0,1,2020
3,952685191,2020000738,01/16/2020 20:30,[SSPD]-DOMESTIC DISPUTE,DOMESTIC DISPUTE,NaN,700 Block JEFFERSON DR,NaN,SANDY SPRINGS,GA,...,-84.357805,1/17/2020 7:38,1/17/2020 23:39,POINT (-84.35780518461924 33.96712149775683),20,4,Family Offense,212686.0,1,2020
4,952704706,2020000729,01/16/2020 16:57,[SSPD]-HIT AND RUN,HIT AND RUN,NaN,200 Block & GLENRIDGE DR,NaN,SANDY SPRINGS,GA,...,-84.361732,1/17/2020 14:38,1/17/2020 23:39,POINT (-84.3617320007644 33.91009075598981),16,4,Traffic,212687.0,1,2020

In [62]:
df_train = df
df.head()

,incident_id,case_number,incident_datetime,incident_type_primary,incident_description,clearance_type,address_1,address_2,city,state,...,longitude,created_at,updated_at,location,hour_of_day,day_of_week,parent_incident_type,Beats Shapes,incident_month,incident_year
0,952728267,2020000781,01/17/2020 1:30:29 PM,[SSPD]-LARCENY-FROM VEHICLE,LARCENY - FROM VEHICLE,NaN,6400 Block POWERS FERRY RD,NaN,SANDY SPRINGS,GA,...,-84.435246,01/17/2020 10:37:53 PM,01/17/2020 11:39:10 PM,POINT (-84.43524649609589 33.90319187235206),13,5,Theft from Vehicle,212688.0,1,2020
1,952728268,2020000768,01/17/2020 12:10:00 PM,[SSPD]-LARCENY - OTHER OFFENSES,LARCENY - OTHER OFFENSES,NaN,1100 Block PERIMETER CTR W,NaN,SANDY SPRINGS,GA,...,-84.351129,01/17/2020 10:37:53 PM,01/17/2020 11:39:10 PM,POINT (-84.35112853386204 33.93003140731569),12,5,Theft,212689.0,1,2020
2,952704703,2020000743,01/17/2020 2:14:38 AM,[SSPD]-DUI - ALCOHOL,DUI - ALCOHOL,NaN,400 Block & WINDSOR PKWY,NaN,SANDY SPRINGS,GA,...,-84.364235,01/17/2020 2:38:41 PM,01/17/2020 11:39:09 PM,POINT (-84.3642353179997 33.89505417513069),2,5,Traffic,212685.0,1,2020
3,952685191,2020000738,01/16/2020 8:30:22 PM,[SSPD]-DOMESTIC DISPUTE,DOMESTIC DISPUTE,NaN,700 Block JEFFERSON DR,NaN,SANDY SPRINGS,GA,...,-84.357805,01/17/2020 7:38:14 AM,01/17/2020 11:39:08 PM,POINT (-84.35780518461924 33.96712149775683),20,4,Family Offense,212686.0,1,2020
4,952704706,2020000729,01/16/2020 4:57:30 PM,[SSPD]-HIT AND RUN,HIT AND RUN,NaN,200 Block & GLENRIDGE DR,NaN,SANDY SPRINGS,GA,...,-84.361732,01/17/2020 2:38:41 PM,01/17/2020 11:39:07 PM,POINT (-84.3617320007644 33.91009075598981),16,4,Traffic,212687.0,1,2020

In [95]:
from sklearn import preprocessing #preprocessing is used to normalize the data
from sklearn.model_selection import train_test_split #train test split is used for preprocessing

In [96]:
features = ['day_of_week', 'hour_of_day', 'incident_month', 'incident_year', 'latitude', 'longitude']
#day_of_week incident_datetime (split it month and year) hour_of_day longitude latitude

In [97]:
X = df_train[features]
y = df_train['parent_incident_type']

In [98]:
scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X) #Normalizing the feature training set
X

array([[ 0.9850234 , -0.0160431 , -1.60005829,  2.07798161, -0.14586212,
        -0.13192581],
       [ 0.9850234 , -0.1743761 , -1.60005829,  2.07798161, -0.0336842 ,
         0.01153398],
       [ 0.9850234 , -1.75770608, -1.60005829,  2.07798161, -0.17987422,
        -0.01081912],
       ...,
       [ 0.9850234 , -0.0160431 , -1.60005829, -1.52185784,  0.11034063,
         0.00805473],
       [ 0.9850234 , -1.91603907, -1.60005829, -1.52185784, -0.04284462,
        -0.01114773],
       [ 0.9850234 , -1.91603907, -1.60005829, -1.52185784, -0.12188882,
        -0.0355175 ]])

In [99]:
pd.DataFrame(X)

              0         1         2         3         4         5
0      0.985023 -0.016043 -1.600058  2.077982 -0.145862 -0.131926
1      0.985023 -0.174376 -1.600058  2.077982 -0.033684  0.011534
2      0.985023 -1.757706 -1.600058  2.077982 -0.179874 -0.010819
3      0.467930  1.092288 -1.600058  2.077982  0.121337  0.000147
4      0.467930  0.458956 -1.600058  2.077982 -0.117028 -0.006550
...         ...       ...       ...       ...       ...       ...
83538  0.985023 -1.916039 -1.600058 -1.521858 -0.097764 -0.037296
83539  0.985023 -0.016043 -1.600058 -1.521858 -0.092593 -0.036891
83540  0.985023 -0.016043 -1.600058 -1.521858  0.110341  0.008055
83541  0.985023 -1.916039 -1.600058 -1.521858 -0.042845 -0.011148
83542  0.985023 -1.916039 -1.600058 -1.521858 -0.121889 -0.035517

[83543 rows x 6 columns]

In [100]:
#transforming incoming data for evaluation
sample_result = [['6', '14', '4', '2015', '34.5772928', '-83.9594747']]
#'day_of_week', 'hour_of_day', 'incident_month', 'incident_year', 'latitude', 'longitude'

sample_result_transformed = scaler.transform(sample_result)
pd.DataFrame(sample_result_transformed)

          0        1         2         3         4         5
0  1.502117  0.14229 -0.725765  0.278062  2.671594  0.679484

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [102]:
from sklearn import svm

In [113]:
#training
classifier = svm.SVC(kernel='rbf', gamma='auto', C=2)
#kernel available: linear, polynomial, radial basis function
#Large Value of parameter C => small margin
#Small Value of paramerter C => Large margin
classifier.fit(X_train, y_train)

SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [114]:
y_predict = classifier.predict(X_test)

In [115]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_predict))
pd.DataFrame(confusion_matrix(y_test,y_predict))

C:\Users\jeawu\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

                            precision    recall  f1-score   support

                     Arson       0.00      0.00      0.00        12
                   Assault       0.00      0.00      0.00       670
Assault with Deadly Weapon       0.00      0.00      0.00        98
       Breaking & Entering       0.00      0.00      0.00      1045
                  Disorder       0.00      0.00      0.00      1316
                     Drugs       0.00      0.00      0.00       197
            Family Offense       0.00      0.00      0.00       494
                  Homicide       0.00      0.00      0.00         6
                    Liquor       0.00      0.00      0.00         4
            Missing Person       0.00      0.00      0.00       139
                     Other       0.00      0.00      0.00      1685
            Property Crime       0.00      0.00      0.00      2392
 Property Crime Commercial       0.00      0.00      0.00        45
                   Robbery       0.00      0.00      0.00       172
                     Theft       0.00      0.00      0.00      1893
        Theft from Vehicle       0.00      0.00      0.00      1778
          Theft of Vehicle       0.00      0.00      0.00       197
                   Traffic       0.27      1.00      0.42      4485
          Vehicle Recovery       0.00      0.00      0.00        36
           Weapons Offense       0.00      0.00      0.00        45

                  accuracy                           0.27     16709
                 macro avg       0.01      0.05      0.02     16709
              weighted avg       0.07      0.27      0.11     16709

    0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16    17  18  19
0   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0    12   0   0
1   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   670   0   0
2   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0    98   0   0
3   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  1045   0   0
4   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  1316   0   0
5   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   197   0   0
6   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   494   0   0
7   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0     6   0   0
8   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0     4   0   0
9   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   139   0   0
10  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  1685   0   0
11  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  2392   0   0
12  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0    45   0   0
13  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   172   0   0
14  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  1893   0   0
15  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  1778   0   0
16  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   197   0   0
17  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0  4485   0   0
18  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0    36   0   0
19  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0    45   0   0